export const questions: string[] = [
    'Write a JavaScript function to find the largest number in an array.',
    'Write a JavaScript function to reverse a string.',
    'Write a JavaScript function to check if a given number is prime.',
    'Write a JavaScript function to remove duplicate elements from an array.',
    'Write a JavaScript function to check if a given string is a palindrome.',
    'Write a JavaScript function to sort an array of objects based on a specific property.',
    'Write a JavaScript function to calculate the factorial of a number.',
    'Write a JavaScript function to shuffle an array.',
    'Write a JavaScript function to find the sum of all numbers in an array.',
    'Write a JavaScript function to check if a given year is a leap year.',
    'Write a JavaScript function to capitalize the first letter of each word in a string.',
    'Write a JavaScript function to find the intersection of two arrays.',
    'Write a JavaScript function to convert a string to camel case.',
    'Write a JavaScript function to find the index of a given element in an array.',
    'Write a JavaScript function to remove a specific element from an array.',
    'Write a JavaScript function to calculate the Fibonacci sequence up to a given number of terms.',
    'Write a JavaScript function to count the occurrences of a specific element in an array.',
    'Write a JavaScript function to find the longest word in a string.',
    'Write a JavaScript function to check if a given string is an anagram of another string.',
    'Write a JavaScript function to remove all falsy values from an array.',
];
